# SPDX-License-Identifier: MIT
import os
import rtconfig

SIFLI_SDK = os.getenv('SIFLI_SDK')
if not SIFLI_SDK:
    print('Please source export.sh in the SiFli SDK first.')
    exit()
from building import *

PrepareEnv()

CAMERA_SOFTWARE_ROOT = os.path.abspath(
    os.path.join(GetCurrentDir(), '../../../..', 'software'))
CAMERA_SW_ISP_RUN_ON_ACPU = GetDepend(['CAMERA_SW_ISP_RUN_ON_ACPU'])
CAMERA_SW_JPEG_RUN_ON_ACPU = GetDepend(['CAMERA_SW_JPEG_RUN_ON_ACPU'])
CAMERA_SW_JPEG_ENCODER = GetDepend(['CAMERA_SW_JPEG_ENCODER'])
CAMERA_SW_JPEG_DECODER = GetDepend(['CAMERA_SW_JPEG_DECODER'])
Export('SIFLI_SDK', 'CAMERA_SOFTWARE_ROOT',
       'CAMERA_SW_ISP_RUN_ON_ACPU', 'CAMERA_SW_JPEG_RUN_ON_ACPU',
       'CAMERA_SW_JPEG_ENCODER', 'CAMERA_SW_JPEG_DECODER')

AddBootLoader(SIFLI_SDK, rtconfig.CHIP)
AddChildProj('acpu', '../acpu', False, core='ACPU')
SifliEnv()

target = rtconfig.OUTPUT_DIR + rtconfig.TARGET_NAME + '.' + rtconfig.TARGET_EXT
objects = PrepareBuilding(None)
env = GetCurrentEnv()
DoBuilding(target, objects)
AddFTAB(SIFLI_SDK, rtconfig.CHIP, env)
GenDownloadScript(env)
