# SPDX-License-Identifier: MIT
import os
from building import *

Import('SIFLI_SDK')

cwd = GetCurrentDir()
root = os.path.abspath(os.path.join(cwd, '../../../..', 'software'))
group = DefineGroup(
    'Camera Software ACPU Example', Glob('*.c'), depend=[''],
    CPPPATH=[os.path.join(cwd, '../../include'),
             os.path.join(root, 'isp/include'),
             os.path.join(root, 'jpeg/include'),
             os.path.join(SIFLI_SDK, 'middleware/acpu_ctrl')])
Return('group')
