# SPDX-License-Identifier: Apache-2.0
import os
import rtconfig

SIFLI_SDK = os.getenv('SIFLI_SDK')
if not SIFLI_SDK:
    print('Please source export.sh in the SiFli SDK first.')
    exit()
from building import *

PrepareEnv()

CAMERA_SW_JPEG_ROOT = os.path.abspath(
    os.path.join(GetCurrentDir(), '../../../software/jpeg'))
Export('SIFLI_SDK', 'CAMERA_SW_JPEG_ROOT')

AddBootLoader(SIFLI_SDK, rtconfig.CHIP)
SifliEnv()

target = rtconfig.OUTPUT_DIR + rtconfig.TARGET_NAME + '.' + rtconfig.TARGET_EXT
objects = PrepareBuilding(None)
env = GetCurrentEnv()
DoBuilding(target, objects)
AddFTAB(SIFLI_SDK, rtconfig.CHIP, env)
GenDownloadScript(env)
