# CONFIG_BSP_ENABLE_AUD_PRC is not set
# CONFIG_BSP_ENABLE_AUD_CODEC is not set
CONFIG_BSP_USING_SPI1=y
# CONFIG_BSP_USING_LCD is not set
# CONFIG_BSP_USING_KEY1 is not set
# CONFIG_BSP_USING_LED1 is not set
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_USING_SPI_MSD=y
CONFIG_RT_USING_MEMHEAP=y
CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_SENSOR_USING_GC032A=y
CONFIG_CAMERA_GC032A_INTERFACE_SERIAL_2BIT=y
CONFIG_CAMERA_READ_TIMEOUT_MS=10000
CONFIG_CAMERA_SCCB_MAX_HZ=200000
