import os
from building import *

cwd = GetCurrentDir()
camera_root = os.path.normpath(os.path.join(cwd, '../../../'))

# Add source code
src = Glob('*.c')
inc = [
    camera_root + '/camera/handle',
]
group = DefineGroup('Applications', src, depend=[''], CPPPATH=inc)

Return('group')
