# SPDX-License-Identifier: MIT
import os
from building import *

Import('CAMERA_SW_ISP_RUN_ON_ACPU', 'CAMERA_SW_JPEG_RUN_ON_ACPU',
       'CAMERA_SW_JPEG_ENCODER', 'CAMERA_SW_JPEG_DECODER', 'SIFLI_SDK')

cwd = GetCurrentDir()
root = os.path.abspath(os.path.join(cwd, '../../../..', 'software'))
defines = []
if CAMERA_SW_ISP_RUN_ON_ACPU:
    defines.append('CAMERA_SW_ACPU_ISP')
if CAMERA_SW_JPEG_RUN_ON_ACPU and CAMERA_SW_JPEG_ENCODER:
    defines.append('CAMERA_SW_ACPU_JPEG_ENCODER')
if CAMERA_SW_JPEG_RUN_ON_ACPU and CAMERA_SW_JPEG_DECODER:
    defines.append('CAMERA_SW_ACPU_JPEG_DECODER')

group = DefineGroup(
    'Camera Software ACPU Worker', ['camera_sw_acpu_worker.c'], depend=[''],
    CPPPATH=[os.path.join(cwd, '../../include'),
             os.path.join(root, 'isp/include'),
             os.path.join(root, 'jpeg/include')],
    CPPDEFINES=defines)
Return('group')
